# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f29bf698569d1cccc8072bed646ad8cd3f13647b8b0bc1886c751b253feba328e4e1c61ac17e839db9f3034d2c5e7c0c780cfeb710120942207b06b74681945

test:
  secret_key_base: a60d3ee0514ee67b253e599f437fa3e857cf9d883165a8addc4b9e51a5c2b5d3bf77adee5b6f5c3c7f812858be1d5942133a3dff37875b174d10603db7a4051e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
